baseURL: "https://mingzelucasni.github.io/" 
title: Mingze Lucas Ni
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: /publication/
          weight: 1
        - name: Interests
          url: /interests/
          weight: 2
        - name: Projects
          url: /projects/
          weight: 3
        - name: Resume
          url: /CV_Lucas.pdf
          weight: 4
        - name: Ancestry
          url: /ancestry/
          weight: 5



params:
    description: "Welcome to my personal website!"
    author: Mingze Lucas Ni
    googleAnalyticsID: "G-LG3FT0FV6E"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mingze Lucas Ni
          subtitle: "Mingze Ni is a Postdoctoral Researcher in machine learning at the University of Technology Sydney. His research interests lie in adversarial machine learning, Markov Chain Monte Carlo (MCMC) methods, combinatorial optimization, and Natural Language Processing (NLP)."
          imageUrl: "/profile.jpg"
          imageWidth: 133
          imageHeight: 165
          imageTitle: Mingze Lucas Ni
          buttons:

            - name: Publications
              url: /publication/

            - name: Interests
              url: /interests/

            - name: Projects
              url: /projects/

            - name: Resume
              url: /CV_Lucas.pdf

            - name: Ancestry
              url: /ancestry/


    socialIcons:
        - name: Email
          url: "mailto:mingze.ni@uts.edu.au"
        - name: homepage
          url: "https://profiles.uts.edu.au/mingze.ni"
        - name: Google Scholar
          url: "https://scholar.google.com/citations?user=eGc81EIAAAAJ&hl=en"
        - name: GitHub
          url: "https://github.com/MingzeLucasNi"
        - name: Orcid
          url: "https://orcid.org/0000-0003-1220-365X"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Mingze Lucas Ni"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
